---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Source: https://www.r-bloggers.com/extracting-exif-data-from-photos-using-r/
```{r}
library(exifr)
library(dplyr)
library(leaflet)
```


Now set your working director the a folder that holds the photos in questions. We can then get the names of all the photos straight into R's memory like this:

```{r}
#Clear fodler
junk <- dir(path = "BestOf", pattern = ".JPG")
file.remove(paste0("BestOf/", junk))

#files <- list.files(path="Pictures",pattern = "*.JPG")
#dat <- exifr(files)


#Read EXIF-Data
dat <- read_exif(path="Pictures",recursive=T)
dat$Rating
dat$ImageDescription
dat$SourceFile
creation=as.POSIXct(dat$CreateDate, format = "%Y:%m:%d %H:%M:%S")
check=creation > "2017-10-14 12:30:00"
dat$check=check

#Check conditions
result <- filter(dat, dat$check == TRUE)
result

# copy the files to the new folder
file.copy(result$SourceFile, "BestOf")



```

#Alternative
You can get all the files and then loop using lapply and apply whatever function you want to apply as follows:
```{r}
files <- list.files(path="path/to/dir", pattern="*.txt", full.names=T, recursive=FALSE)
lapply(files, function(x) {
    t <- read.table(x, header=T) # load file
    # apply function
    out <- function(t)
    # write to file
    write.table(out, "path/to/output", sep="\t", quote=F, row.names=F, col.names=T)
})
```


# Text Manipulation
Source: https://cran.r-project.org/web/packages/magick/vignettes/intro.html
```{r}
library(magick)
pic <- image_read(dat$SourceFile[1])
title=dat$ImageDescription[1]
image_info(pic)


#image_browse(pic)


# Add 20px left/right and 10px top/bottom
pic = image_border(pic, "#FFFFFF", "200x100")
pic=image_rotate(pic,90)
# Fonts may require ImageMagick has fontconfig
#pic = image_annotate(pic, "The quick brown fox", font = 'Times', size = 60)
pic = image_annotate(pic, title, size = 150, gravity = "south", color = "red")
#pic=image_annotate(pic, "Some text", location = geometry_point(100, 200), size = 24)
pic = image_rotate(pic, -90)
# Render svg to png bitmap
image_write(pic, path = "pic.jpg", format = "jpg")



```


